services:
  sake-migrator:
    build:
      context: .
      dockerfile: ./sake/dockerfile
      args:
        PUBLIC_WEBAPP_VERSION: ${PUBLIC_WEBAPP_VERSION:-dev-local}
        PUBLIC_WEBAPP_GIT_TAG: ${PUBLIC_WEBAPP_GIT_TAG:-}
        PUBLIC_WEBAPP_COMMIT_SHA: ${PUBLIC_WEBAPP_COMMIT_SHA:-}
        PUBLIC_WEBAPP_RELEASED_AT: ${PUBLIC_WEBAPP_RELEASED_AT:-}
    image: sake
    container_name: sake-migrator
    command: ["bun", "run", "db:migrate"]
    env_file:
      - ./sake/.env
    # networks:
    #   - caddy_net
    restart: "no"

  sake: 
    build:
      context: .
      dockerfile: ./sake/dockerfile
      args:
        PUBLIC_WEBAPP_VERSION: ${PUBLIC_WEBAPP_VERSION:-dev-local}
        PUBLIC_WEBAPP_GIT_TAG: ${PUBLIC_WEBAPP_GIT_TAG:-}
        PUBLIC_WEBAPP_COMMIT_SHA: ${PUBLIC_WEBAPP_COMMIT_SHA:-}
        PUBLIC_WEBAPP_RELEASED_AT: ${PUBLIC_WEBAPP_RELEASED_AT:-}
    image: sake
    container_name: sake
    depends_on:
      sake-migrator:
        condition: service_completed_successfully
    ports:
      - "5173:3000"
    environment:
      - PUBLIC_WEBAPP_VERSION=${PUBLIC_WEBAPP_VERSION:-dev-local}
      - PUBLIC_WEBAPP_GIT_TAG=${PUBLIC_WEBAPP_GIT_TAG:-}
      - PUBLIC_WEBAPP_COMMIT_SHA=${PUBLIC_WEBAPP_COMMIT_SHA:-}
      - PUBLIC_WEBAPP_RELEASED_AT=${PUBLIC_WEBAPP_RELEASED_AT:-}
    env_file:
      - ./sake/.env
    volumes:
      - ./koreaderPlugins/sake.koplugin:/app/koreaderPlugins/sake.koplugin:ro
    # networks:
    #   - caddy_net

# If a reverse proxy like caddy is used
# networks:
#   caddy_net:
#     external: true
